# tensor的创建与运算

In [12]:
import torch
# 1. 先创建两个简单的 Tensor (张量)
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
print(f"原始数据 a: {a}")
print(f"原始数据 b: {b}")

原始数据 a: tensor([1, 2, 3])
原始数据 b: tensor([4, 5, 6])


In [13]:
# 2. 加法 (Addition)
c_add = a + b
print(f"加法 (a + b): {c_add}")
# 3. 减法 (Subtraction)
c_sub = a - b
print(f"减法 (a - b): {c_sub}")

加法 (a + b): tensor([5, 7, 9])
减法 (a - b): tensor([-3, -3, -3])


In [14]:
# 4.1 元素级乘法 (Element-wise)
c_mul_element = a * b
print(f"元素级乘法 (a * b): {c_mul_element}")
# 4.2 矩阵乘法 (Matrix Multiplication) - 这个以后学深度学习会经常遇到
c_mul_matrix = a @ b
print(f"矩阵/点积乘法 (a @ b): {c_mul_matrix}")

元素级乘法 (a * b): tensor([ 4, 10, 18])
矩阵/点积乘法 (a @ b): 32


In [15]:
# 5. 除法 (Division)
c_div = a / b
print(f"除法 (a / b): {c_div}")
# 6.  bonus: 广播机制 (Broadcasting) - 很实用！
# 意思是：Tensor 可以直接和一个数字（标量）计算
d = a + 10 # 每个元素都加 10
print(f"广播机制 (a + 10): {d}")

除法 (a / b): tensor([0.2500, 0.4000, 0.5000])
广播机制 (a + 10): tensor([11, 12, 13])


In [16]:
# 7. 矩阵乘法 (Matrix Multiplication)
# 矩阵 A: 形状 (2, 3) -> 2行，3列
A = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])
# 矩阵 B: 形状 (3, 2) -> 3行，2列
B = torch.tensor([
    [7, 8],
    [9, 10],
    [11, 12]
])
print(f"形状 A: {A.shape}\n")
print(f"形状 B: {B.shape}\n")
# 规则：(2, 3) @ (3, 2) -> 结果形状是 (2, 2)
C = A @ B
# 或者写成: C = torch.matmul(A, B)
print(C)
C.shape

形状 A: torch.Size([2, 3])

形状 B: torch.Size([3, 2])

tensor([[ 58,  64],
        [139, 154]])


torch.Size([2, 2])

In [11]:
x = torch.tensor([1, 2, 3, 4])
print(f"原始数据 x: {x}")

# 平方、立方 (Power)
# 使用 ** 运算符
x_squared = x ** 2  # 平方
x_cubed = x ** 3    # 立方

print(f"\n平方 (x^2): {x_squared}")
print(f"立方 (x^3): {x_cubed}")

# 自然指数 (Exponential)
# 使用 torch.exp()
x_exp = torch.exp(x)
print(f"\n自然指数 e^x: {x_exp}")

# 平方根 (Square Root)
# 使用 torch.sqrt() 或 x ** 0.5
y = torch.tensor([4, 9, 16, 25])
y_sqrt = torch.sqrt(y)
print(f"\n平方根 sqrt(y): {y_sqrt}")

原始数据 x: tensor([1, 2, 3, 4])

平方 (x^2): tensor([ 1,  4,  9, 16])
立方 (x^3): tensor([ 1,  8, 27, 64])

自然指数 e^x: tensor([ 2.7183,  7.3891, 20.0855, 54.5981])

平方根 sqrt(y): tensor([2., 3., 4., 5.])


# tensor的操作

In [22]:
# tensor变为其他数据结构
x = torch.tensor([2.0, 2.0, 6.0, 8.0])  # 变为列表
print(x.tolist())
y = torch.tensor(1.0)  # 单个元素
print(y.item())
z = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]])
print(z.tolist())

[2.0, 2.0, 6.0, 8.0]
1.0
[[1, 2, 3], [4, 5, 6]]


In [34]:
# tensor切片
x = torch.tensor([2.0, 9.0, 6.0, 8.0])
print(x[0])
print(x[1:3])

# tensor赋值
x[0] = 100
print(x)


# tensor排序
print(x.sort())
#tensor矩阵按照每行排序
x = torch.tensor([
    [2.0, 9.0, 6.0],
    [8.0, 1.0, 3.0]])
print(x.sort(dim=1))
#按照列排序
print(x.sort(dim=0))


tensor(2.)
tensor([9., 6.])
tensor([100.,   9.,   6.,   8.])
torch.return_types.sort(
values=tensor([  6.,   8.,   9., 100.]),
indices=tensor([2, 3, 1, 0]))
torch.return_types.sort(
values=tensor([[2., 6., 9.],
        [1., 3., 8.]]),
indices=tensor([[0, 2, 1],
        [1, 2, 0]]))
torch.return_types.sort(
values=tensor([[2., 1., 3.],
        [8., 9., 6.]]),
indices=tensor([[0, 1, 1],
        [1, 0, 0]]))
